#!/usr/bin/env python3
"""Analyze compact rotation bottleneck geometry and motion-conditioned alignment.

This script is the final post-training analysis for the combined experiment:

    (1) compact/task-relevant rotation bottleneck
    (2) motion-conditioned representation consistency/alignment

It analyzes exported compact rotation representations and optionally the
pair archive produced by:

    scripts/build_rotation_motion_alignment_pairs.py

Expected per-sequence NPZ
-------------------------
Each ``rotation_representations.npz`` should contain:

    rotation_rep
        Compact rotation representation z_R.
        Shape: [N, D]

    rotation_gt_array or rotation_gt
        Ground-truth relative rotations.
        Shape: [N, 3]

    translation_gt_array or translation_gt
        Ground-truth relative translations.
        Shape: [N, 3]

    motion_regime_array or motion_regime
        Motion regime assignment derived using training-set thresholds.
        Shape: [N]

        0 = low
        1 = medium
        2 = high

Optional pair NPZ
-----------------
The output from ``build_rotation_motion_alignment_pairs.py``:

    anchor_rep
    partner_rep
    pair_label
    anchor_regime
    partner_regime
    same_regime
    same_sequence
    euclidean_distance
    cosine_similarity

Questions answered
------------------
1. Is the bottleneck numerically healthy?
2. How much representation variance is retained?
3. Can rotation still be decoded from z_R?
4. Do representations separate by motion regime?
5. Are same-regime representations aligned across sequences?
6. Does cross-sequence alignment improve relative to regime mismatch?
7. How much sequence identity remains linearly decodable?
8. Does sequence 10 occupy the same regime-conditioned geometry as
   training sequences?

Example
-------
python3 scripts/analyze_rotation_bottleneck_alignment.py \\
    --input experiments/rotation_alignment/00/rotation_representations.npz \\
    --input experiments/rotation_alignment/01/rotation_representations.npz \\
    --input experiments/rotation_alignment/02/rotation_representations.npz \\
    --input experiments/rotation_alignment/03/rotation_representations.npz \\
    --input experiments/rotation_alignment/04/rotation_representations.npz \\
    --input experiments/rotation_alignment/05/rotation_representations.npz \\
    --input experiments/rotation_alignment/06/rotation_representations.npz \\
    --input experiments/rotation_alignment/07/rotation_representations.npz \\
    --input experiments/rotation_alignment/08/rotation_representations.npz \\
    --input experiments/rotation_alignment/09/rotation_representations.npz \\
    --input experiments/rotation_alignment/10/rotation_representations.npz \\
    --train-sequences 00 01 02 03 04 05 06 07 08 \\
    --validation-sequences 09 \\
    --test-sequences 10 \\
    --pairs \
        experiments/rotation_motion_alignment_pairs/rotation_motion_alignment_pairs.npz \\
    --output-dir experiments/rotation_bottleneck_alignment_analysis

Outputs
-------
<output-dir>/
├── analysis_summary.txt
├── representation_statistics.csv
├── regime_statistics.csv
├── sequence_statistics.csv
├── sequence_regime_centroids.csv
├── centroid_distances.csv
├── rotation_linear_probe.csv
├── sequence_probe.csv
├── pair_geometry.csv
└── principal_components.npz

No model parameters are modified.
"""

from __future__ import annotations

import argparse
import csv
import math
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Mapping, Optional, Sequence, Tuple

import numpy as np


REGIME_NAMES = {
    0: "low",
    1: "medium",
    2: "high",
}


@dataclass(frozen=True)
class SequenceBlock:
    """One sequence's exported representation data."""

    sequence: str
    path: Path
    representation: np.ndarray
    rotation_gt: np.ndarray
    translation_gt: np.ndarray
    motion_regime: np.ndarray


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Analyze compact rotation representation geometry and "
            "motion-conditioned cross-sequence alignment."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    parser.add_argument(
        "--input",
        dest="inputs",
        action="append",
        type=Path,
        required=True,
        help=(
            "Per-sequence rotation_representations.npz. "
            "Repeat --input for every sequence."
        ),
    )

    parser.add_argument(
        "--pairs",
        type=Path,
        default=None,
        help=(
            "Optional rotation_motion_alignment_pairs.npz generated by "
            "build_rotation_motion_alignment_pairs.py."
        ),
    )

    parser.add_argument(
        "--train-sequences",
        nargs="+",
        default=[
            "00",
            "01",
            "02",
            "03",
            "04",
            "05",
            "06",
            "07",
            "08",
        ],
        help="Sequences defining the training representation domain.",
    )

    parser.add_argument(
        "--validation-sequences",
        nargs="+",
        default=["09"],
        help="Validation sequences.",
    )

    parser.add_argument(
        "--test-sequences",
        nargs="+",
        default=["10"],
        help="Held-out test sequences.",
    )

    parser.add_argument(
        "--ridge-alpha",
        type=float,
        default=1.0e-3,
        help="Ridge regularization for rotation linear probes.",
    )

    parser.add_argument(
        "--sequence-probe-alpha",
        type=float,
        default=1.0,
        help=(
            "Ridge regularization used by one-vs-rest sequence "
            "identity probe."
        ),
    )

    parser.add_argument(
        "--pca-components",
        type=int,
        default=16,
        help="Number of principal components saved for diagnostics.",
    )

    parser.add_argument(
        "--normalize-representations",
        action="store_true",
        help=(
            "L2-normalize representation rows before geometry/probe analysis."
        ),
    )

    parser.add_argument(
        "--output-dir",
        type=Path,
        required=True,
        help="Directory for analysis outputs.",
    )

    return parser.parse_args()


def validate_args(
    args: argparse.Namespace,
) -> None:
    if not args.inputs:
        raise ValueError(
            "At least one --input is required."
        )

    for path in args.inputs:
        if not path.is_file():
            raise FileNotFoundError(
                f"Input file does not exist: {path}"
            )

    if args.pairs is not None and not args.pairs.is_file():
        raise FileNotFoundError(
            f"Pair file does not exist: {args.pairs}"
        )

    if args.ridge_alpha < 0:
        raise ValueError(
            "--ridge-alpha cannot be negative."
        )

    if args.sequence_probe_alpha < 0:
        raise ValueError(
            "--sequence-probe-alpha cannot be negative."
        )

    if args.pca_components <= 0:
        raise ValueError(
            "--pca-components must be positive."
        )


def infer_sequence(
    path: Path,
) -> str:
    for component in reversed(
        path.parts[:-1]
    ):
        if re.fullmatch(
            r"\d{1,2}",
            component,
        ):
            return component.zfill(2)

    return path.parent.name


def resolve_npz_key(
    archive: np.lib.npyio.NpzFile,
    candidates: Sequence[str],
    description: str,
) -> str:
    for key in candidates:
        if key in archive.files:
            return key

    raise KeyError(
        f"Missing {description}. "
        f"Accepted keys={list(candidates)}, "
        f"available={archive.files}."
    )


def l2_normalize_rows(
    x: np.ndarray,
    eps: float = 1.0e-12,
) -> np.ndarray:
    norms = np.linalg.norm(
        x,
        axis=1,
        keepdims=True,
    )

    return (
        x
        / np.maximum(
            norms,
            eps,
        )
    )


def load_sequence_block(
    path: Path,
    normalize: bool,
) -> SequenceBlock:
    sequence = infer_sequence(
        path
    )

    with np.load(
        path,
        allow_pickle=False,
    ) as archive:
        representation_key = resolve_npz_key(
            archive,
            (
                "rotation_rep",
                "rotation_representation",
            ),
            "rotation representation",
        )

        rotation_key = resolve_npz_key(
            archive,
            (
                "rotation_gt_array",
                "rotation_gt",
            ),
            "rotation GT",
        )

        translation_key = resolve_npz_key(
            archive,
            (
                "translation_gt_array",
                "translation_gt",
            ),
            "translation GT",
        )

        regime_key = resolve_npz_key(
            archive,
            (
                "motion_regime_array",
                "motion_regime",
            ),
            "motion regime",
        )

        representation = np.asarray(
            archive[
                representation_key
            ],
            dtype=np.float64,
        )

        rotation_gt = np.asarray(
            archive[
                rotation_key
            ],
            dtype=np.float64,
        )

        translation_gt = np.asarray(
            archive[
                translation_key
            ],
            dtype=np.float64,
        )

        motion_regime = np.asarray(
            archive[
                regime_key
            ]
        ).reshape(-1)

    if representation.ndim != 2:
        raise ValueError(
            f"{path}: representation must be [N, D], "
            f"received {representation.shape}."
        )

    n_samples = representation.shape[0]

    if rotation_gt.shape != (
        n_samples,
        3,
    ):
        raise ValueError(
            f"{path}: rotation_gt must be "
            f"({n_samples}, 3), "
            f"received {rotation_gt.shape}."
        )

    if translation_gt.shape != (
        n_samples,
        3,
    ):
        raise ValueError(
            f"{path}: translation_gt must be "
            f"({n_samples}, 3), "
            f"received {translation_gt.shape}."
        )

    if motion_regime.shape != (
        n_samples,
    ):
        raise ValueError(
            f"{path}: motion_regime must be "
            f"({n_samples},), "
            f"received {motion_regime.shape}."
        )

    for name, array in (
        ("representation", representation),
        ("rotation_gt", rotation_gt),
        ("translation_gt", translation_gt),
    ):
        if not np.all(
            np.isfinite(array)
        ):
            raise ValueError(
                f"{path}: {name} contains "
                "NaN or infinity."
            )

    motion_regime = np.rint(
        motion_regime
    ).astype(
        np.int64
    )

    invalid = sorted(
        set(
            motion_regime.tolist()
        )
        - set(
            REGIME_NAMES.keys()
        )
    )

    if invalid:
        raise ValueError(
            f"{path}: invalid motion regime IDs "
            f"{invalid}."
        )

    if normalize:
        representation = (
            l2_normalize_rows(
                representation
            )
        )

    return SequenceBlock(
        sequence=sequence,
        path=path,
        representation=representation,
        rotation_gt=rotation_gt,
        translation_gt=translation_gt,
        motion_regime=motion_regime,
    )


def load_all_blocks(
    paths: Sequence[Path],
    normalize: bool,
) -> List[SequenceBlock]:
    blocks: List[
        SequenceBlock
    ] = []

    expected_dimension: Optional[
        int
    ] = None

    seen_sequences = set()

    for path in paths:
        block = load_sequence_block(
            path=path,
            normalize=normalize,
        )

        if block.sequence in seen_sequences:
            raise ValueError(
                "Duplicate sequence export supplied: "
                f"{block.sequence}."
            )

        seen_sequences.add(
            block.sequence
        )

        if expected_dimension is None:
            expected_dimension = int(
                block.representation.shape[
                    1
                ]
            )

        elif (
            block.representation.shape[
                1
            ]
            != expected_dimension
        ):
            raise ValueError(
                "Representation dimensions do not "
                "match across inputs. "
                f"Expected {expected_dimension}, "
                f"received "
                f"{block.representation.shape[1]} "
                f"for sequence {block.sequence}."
            )

        blocks.append(
            block
        )

        print(
            f"Loaded sequence "
            f"{block.sequence}: "
            f"N={block.representation.shape[0]} "
            f"D={block.representation.shape[1]}"
        )

    return blocks


def concatenate_blocks(
    blocks: Sequence[SequenceBlock],
) -> Tuple[
    np.ndarray,
    np.ndarray,
    np.ndarray,
    np.ndarray,
    np.ndarray,
]:
    representations = np.concatenate(
        [
            block.representation
            for block in blocks
        ],
        axis=0,
    )

    rotations = np.concatenate(
        [
            block.rotation_gt
            for block in blocks
        ],
        axis=0,
    )

    translations = np.concatenate(
        [
            block.translation_gt
            for block in blocks
        ],
        axis=0,
    )

    regimes = np.concatenate(
        [
            block.motion_regime
            for block in blocks
        ],
        axis=0,
    )

    sequences = np.concatenate(
        [
            np.asarray(
                [
                    block.sequence
                ]
                * block.representation.shape[
                    0
                ]
            )
            for block in blocks
        ],
        axis=0,
    )

    return (
        representations,
        rotations,
        translations,
        regimes,
        sequences,
    )


def centroid(
    x: np.ndarray,
) -> np.ndarray:
    if x.shape[0] == 0:
        raise ValueError(
            "Cannot calculate centroid of "
            "an empty array."
        )

    return x.mean(
        axis=0
    )


def rms_scale(
    x: np.ndarray,
) -> float:
    if x.size == 0:
        return float("nan")

    return float(
        np.sqrt(
            np.mean(
                x ** 2
            )
        )
    )


def total_variance(
    x: np.ndarray,
) -> float:
    if x.shape[0] <= 1:
        return 0.0

    return float(
        np.var(
            x,
            axis=0,
            ddof=1,
        ).sum()
    )


def within_spread(
    x: np.ndarray,
) -> float:
    if x.shape[0] == 0:
        return float("nan")

    c = centroid(
        x
    )

    return float(
        np.sqrt(
            np.mean(
                np.sum(
                    (
                        x
                        - c
                    )
                    ** 2,
                    axis=1,
                )
            )
        )
    )


def cosine_similarity(
    a: np.ndarray,
    b: np.ndarray,
    eps: float = 1.0e-12,
) -> float:
    denominator = (
        np.linalg.norm(a)
        * np.linalg.norm(b)
    )

    if denominator <= eps:
        return float("nan")

    return float(
        np.dot(a, b)
        / denominator
    )


def angle_degrees(
    a: np.ndarray,
    b: np.ndarray,
) -> float:
    cosine = cosine_similarity(
        a,
        b,
    )

    if not math.isfinite(
        cosine
    ):
        return float("nan")

    cosine = float(
        np.clip(
            cosine,
            -1.0,
            1.0,
        )
    )

    return float(
        np.degrees(
            np.arccos(
                cosine
            )
        )
    )


def write_csv(
    path: Path,
    rows: Sequence[
        Mapping[str, object]
    ],
) -> None:
    if not rows:
        return

    fieldnames = list(
        rows[0].keys()
    )

    with path.open(
        "w",
        encoding="utf-8",
        newline="",
    ) as file:
        writer = csv.DictWriter(
            file,
            fieldnames=fieldnames,
        )

        writer.writeheader()

        for row in rows:
            writer.writerow(
                row
            )


def representation_statistics(
    x: np.ndarray,
) -> Dict[str, object]:
    norms = np.linalg.norm(
        x,
        axis=1,
    )

    c = centroid(
        x
    )

    return {
        "n": int(
            x.shape[0]
        ),
        "dimension": int(
            x.shape[1]
        ),
        "mean_norm": float(
            norms.mean()
        ),
        "std_norm": float(
            norms.std()
        ),
        "centroid_norm": float(
            np.linalg.norm(c)
        ),
        "within_spread": (
            within_spread(x)
        ),
        "total_variance": (
            total_variance(x)
        ),
        "rms_scale": (
            rms_scale(x)
        ),
        "minimum": float(
            np.min(x)
        ),
        "maximum": float(
            np.max(x)
        ),
    }


def compute_sequence_statistics(
    blocks: Sequence[SequenceBlock],
) -> List[
    Dict[str, object]
]:
    rows: List[
        Dict[str, object]
    ] = []

    for block in sorted(
        blocks,
        key=lambda item: item.sequence,
    ):
        stats = representation_statistics(
            block.representation
        )

        row = {
            "sequence": (
                block.sequence
            ),
            **stats,
        }

        rows.append(
            row
        )

    return rows


def compute_regime_statistics(
    representations: np.ndarray,
    regimes: np.ndarray,
) -> List[
    Dict[str, object]
]:
    rows: List[
        Dict[str, object]
    ] = []

    for regime in sorted(
        REGIME_NAMES
    ):
        mask = (
            regimes == regime
        )

        if not np.any(
            mask
        ):
            continue

        stats = (
            representation_statistics(
                representations[
                    mask
                ]
            )
        )

        rows.append(
            {
                "regime": regime,
                "regime_name": (
                    REGIME_NAMES[
                        regime
                    ]
                ),
                **stats,
            }
        )

    return rows


def compute_sequence_regime_centroids(
    blocks: Sequence[SequenceBlock],
) -> Tuple[
    List[Dict[str, object]],
    Dict[
        Tuple[str, int],
        np.ndarray,
    ],
]:
    rows: List[
        Dict[str, object]
    ] = []

    centroids: Dict[
        Tuple[str, int],
        np.ndarray,
    ] = {}

    for block in sorted(
        blocks,
        key=lambda item: item.sequence,
    ):
        for regime in sorted(
            REGIME_NAMES
        ):
            mask = (
                block.motion_regime
                == regime
            )

            if not np.any(
                mask
            ):
                continue

            subset = (
                block.representation[
                    mask
                ]
            )

            c = centroid(
                subset
            )

            centroids[
                (
                    block.sequence,
                    regime,
                )
            ] = c

            rows.append(
                {
                    "sequence": (
                        block.sequence
                    ),
                    "regime": regime,
                    "regime_name": (
                        REGIME_NAMES[
                            regime
                        ]
                    ),
                    "n": int(
                        subset.shape[0]
                    ),
                    "centroid_norm": float(
                        np.linalg.norm(c)
                    ),
                    "within_spread": (
                        within_spread(
                            subset
                        )
                    ),
                }
            )

    return (
        rows,
        centroids,
    )


def compute_centroid_distances(
    centroids: Mapping[
        Tuple[str, int],
        np.ndarray,
    ],
) -> List[
    Dict[str, object]
]:
    keys = sorted(
        centroids.keys()
    )

    rows: List[
        Dict[str, object]
    ] = []

    for i, first_key in enumerate(
        keys
    ):
        sequence_a, regime_a = (
            first_key
        )

        centroid_a = (
            centroids[
                first_key
            ]
        )

        for second_key in keys[
            i + 1 :
        ]:
            sequence_b, regime_b = (
                second_key
            )

            centroid_b = (
                centroids[
                    second_key
                ]
            )

            distance = float(
                np.linalg.norm(
                    centroid_a
                    - centroid_b
                )
            )

            rows.append(
                {
                    "sequence_a": (
                        sequence_a
                    ),
                    "regime_a": (
                        regime_a
                    ),
                    "regime_a_name": (
                        REGIME_NAMES[
                            regime_a
                        ]
                    ),
                    "sequence_b": (
                        sequence_b
                    ),
                    "regime_b": (
                        regime_b
                    ),
                    "regime_b_name": (
                        REGIME_NAMES[
                            regime_b
                        ]
                    ),
                    "same_sequence": int(
                        sequence_a
                        == sequence_b
                    ),
                    "same_regime": int(
                        regime_a
                        == regime_b
                    ),
                    "euclidean_distance": (
                        distance
                    ),
                    "cosine_similarity": (
                        cosine_similarity(
                            centroid_a,
                            centroid_b,
                        )
                    ),
                    "angle_degrees": (
                        angle_degrees(
                            centroid_a,
                            centroid_b,
                        )
                    ),
                }
            )

    return rows


def ridge_fit(
    x: np.ndarray,
    y: np.ndarray,
    alpha: float,
) -> Tuple[
    np.ndarray,
    np.ndarray,
]:
    """Fit ridge with an unregularized intercept."""

    if x.ndim != 2:
        raise ValueError(
            "x must be 2-D."
        )

    if y.ndim == 1:
        y = y[:, None]

    x_mean = x.mean(
        axis=0,
        keepdims=True,
    )

    y_mean = y.mean(
        axis=0,
        keepdims=True,
    )

    xc = (
        x
        - x_mean
    )

    yc = (
        y
        - y_mean
    )

    dimension = (
        x.shape[1]
    )

    lhs = (
        xc.T @ xc
        + alpha
        * np.eye(
            dimension,
            dtype=np.float64,
        )
    )

    rhs = (
        xc.T
        @ yc
    )

    weights = np.linalg.solve(
        lhs,
        rhs,
    )

    bias = (
        y_mean
        - x_mean
        @ weights
    ).reshape(
        -1
    )

    return (
        weights,
        bias,
    )


def ridge_predict(
    x: np.ndarray,
    weights: np.ndarray,
    bias: np.ndarray,
) -> np.ndarray:
    return (
        x
        @ weights
        + bias
    )


def rmse(
    prediction: np.ndarray,
    target: np.ndarray,
) -> float:
    return float(
        np.sqrt(
            np.mean(
                (
                    prediction
                    - target
                )
                ** 2
            )
        )
    )


def mae(
    prediction: np.ndarray,
    target: np.ndarray,
) -> float:
    return float(
        np.mean(
            np.abs(
                prediction
                - target
            )
        )
    )


def safe_corr(
    first: np.ndarray,
    second: np.ndarray,
) -> float:
    first = np.asarray(
        first
    ).reshape(-1)

    second = np.asarray(
        second
    ).reshape(-1)

    if first.size < 2:
        return float("nan")

    if (
        np.std(first)
        <= 1.0e-12
        or np.std(second)
        <= 1.0e-12
    ):
        return float("nan")

    return float(
        np.corrcoef(
            first,
            second,
        )[0, 1]
    )


def mask_sequences(
    sequences: np.ndarray,
    selected: Sequence[str],
) -> np.ndarray:
    normalized = {
        str(sequence).zfill(2)
        for sequence in selected
    }

    return np.asarray(
        [
            str(value).zfill(2)
            in normalized
            for value in sequences
        ],
        dtype=bool,
    )


def evaluate_rotation_probe(
    representations: np.ndarray,
    rotations: np.ndarray,
    sequences: np.ndarray,
    train_sequences: Sequence[str],
    evaluation_sequences: Sequence[str],
    alpha: float,
    split_name: str,
) -> Dict[str, object]:
    train_mask = mask_sequences(
        sequences,
        train_sequences,
    )

    evaluation_mask = mask_sequences(
        sequences,
        evaluation_sequences,
    )

    if not np.any(
        train_mask
    ):
        raise RuntimeError(
            "Rotation probe contains no "
            "training samples."
        )

    if not np.any(
        evaluation_mask
    ):
        raise RuntimeError(
            f"Rotation probe contains no "
            f"{split_name} samples."
        )

    weights, bias = ridge_fit(
        representations[
            train_mask
        ],
        rotations[
            train_mask
        ],
        alpha=alpha,
    )

    prediction = ridge_predict(
        representations[
            evaluation_mask
        ],
        weights,
        bias,
    )

    target = rotations[
        evaluation_mask
    ]

    return {
        "split": split_name,
        "train_n": int(
            np.count_nonzero(
                train_mask
            )
        ),
        "test_n": int(
            np.count_nonzero(
                evaluation_mask
            )
        ),
        "alpha": float(
            alpha
        ),
        "vector_rmse": rmse(
            prediction,
            target,
        ),
        "vector_mae": mae(
            prediction,
            target,
        ),
        "x_rmse": rmse(
            prediction[:, 0],
            target[:, 0],
        ),
        "y_rmse": rmse(
            prediction[:, 1],
            target[:, 1],
        ),
        "z_rmse": rmse(
            prediction[:, 2],
            target[:, 2],
        ),
        "x_corr": safe_corr(
            prediction[:, 0],
            target[:, 0],
        ),
        "y_corr": safe_corr(
            prediction[:, 1],
            target[:, 1],
        ),
        "z_corr": safe_corr(
            prediction[:, 2],
            target[:, 2],
        ),
    }


def one_hot(
    labels: np.ndarray,
    classes: Sequence[str],
) -> np.ndarray:
    class_to_index = {
        value: index
        for index, value in enumerate(
            classes
        )
    }

    result = np.zeros(
        (
            labels.shape[0],
            len(classes),
        ),
        dtype=np.float64,
    )

    for row_index, label in enumerate(
        labels
    ):
        result[
            row_index,
            class_to_index[
                str(label)
            ],
        ] = 1.0

    return result


def sequence_probe(
    representations: np.ndarray,
    sequences: np.ndarray,
    alpha: float,
) -> Dict[str, object]:
    classes = sorted(
        {
            str(value)
            for value in sequences
        }
    )

    targets = one_hot(
        sequences,
        classes,
    )

    weights, bias = ridge_fit(
        representations,
        targets,
        alpha=alpha,
    )

    scores = ridge_predict(
        representations,
        weights,
        bias,
    )

    predicted_indices = np.argmax(
        scores,
        axis=1,
    )

    true_indices = np.asarray(
        [
            classes.index(
                str(value)
            )
            for value in sequences
        ],
        dtype=np.int64,
    )

    accuracy = float(
        np.mean(
            predicted_indices
            == true_indices
        )
    )

    chance = (
        1.0
        / len(classes)
    )

    return {
        "n": int(
            representations.shape[0]
        ),
        "num_sequences": int(
            len(classes)
        ),
        "alpha": float(
            alpha
        ),
        "training_accuracy": (
            accuracy
        ),
        "chance_accuracy": float(
            chance
        ),
        "accuracy_minus_chance": float(
            accuracy
            - chance
        ),
    }


def compute_pca(
    representations: np.ndarray,
    requested_components: int,
) -> Dict[str, np.ndarray]:
    mean = representations.mean(
        axis=0,
        keepdims=True,
    )

    centered = (
        representations
        - mean
    )

    _, singular_values, vt = (
        np.linalg.svd(
            centered,
            full_matrices=False,
        )
    )

    maximum_components = min(
        requested_components,
        vt.shape[0],
    )

    components = vt[
        :maximum_components
    ]

    projected = (
        centered
        @ components.T
    )

    if representations.shape[0] > 1:
        explained_variance = (
            singular_values ** 2
            / (
                representations.shape[0]
                - 1
            )
        )
    else:
        explained_variance = (
            singular_values ** 2
        )

    total = float(
        explained_variance.sum()
    )

    if total > 0:
        explained_ratio = (
            explained_variance
            / total
        )
    else:
        explained_ratio = (
            np.zeros_like(
                explained_variance
            )
        )

    return {
        "mean": mean.squeeze(0),
        "components": components,
        "projected": projected,
        "explained_variance": (
            explained_variance[
                :maximum_components
            ]
        ),
        "explained_variance_ratio": (
            explained_ratio[
                :maximum_components
            ]
        ),
    }


def summarize_centroid_geometry(
    centroid_rows: Sequence[
        Mapping[str, object]
    ],
) -> Dict[str, float]:
    same_regime_cross_sequence = [
        float(
            row[
                "euclidean_distance"
            ]
        )
        for row in centroid_rows
        if (
            int(
                row[
                    "same_regime"
                ]
            )
            == 1
            and int(
                row[
                    "same_sequence"
                ]
            )
            == 0
        )
    ]

    different_regime_cross_sequence = [
        float(
            row[
                "euclidean_distance"
            ]
        )
        for row in centroid_rows
        if (
            int(
                row[
                    "same_regime"
                ]
            )
            == 0
            and int(
                row[
                    "same_sequence"
                ]
            )
            == 0
        )
    ]

    return {
        "same_regime_cross_sequence_distance": (
            float(
                np.mean(
                    same_regime_cross_sequence
                )
            )
            if same_regime_cross_sequence
            else float("nan")
        ),
        "different_regime_cross_sequence_distance": (
            float(
                np.mean(
                    different_regime_cross_sequence
                )
            )
            if different_regime_cross_sequence
            else float("nan")
        ),
    }


def analyze_pair_archive(
    path: Path,
) -> Tuple[
    List[Dict[str, object]],
    Dict[str, float],
]:
    with np.load(
        path,
        allow_pickle=False,
    ) as archive:
        required = {
            "pair_label",
            "same_regime",
            "same_sequence",
            "euclidean_distance",
            "cosine_similarity",
        }

        missing = required.difference(
            archive.files
        )

        if missing:
            raise KeyError(
                f"{path} missing pair keys: "
                f"{sorted(missing)}."
            )

        pair_label = np.asarray(
            archive[
                "pair_label"
            ]
        ).reshape(-1)

        same_regime = np.asarray(
            archive[
                "same_regime"
            ]
        ).reshape(-1)

        same_sequence = np.asarray(
            archive[
                "same_sequence"
            ]
        ).reshape(-1)

        euclidean = np.asarray(
            archive[
                "euclidean_distance"
            ],
            dtype=np.float64,
        ).reshape(-1)

        cosine = np.asarray(
            archive[
                "cosine_similarity"
            ],
            dtype=np.float64,
        ).reshape(-1)

    n = pair_label.shape[0]

    for array in (
        same_regime,
        same_sequence,
        euclidean,
        cosine,
    ):
        if array.shape[0] != n:
            raise ValueError(
                "Pair archive arrays have "
                "inconsistent lengths."
            )

    rows: List[
        Dict[str, object]
    ] = []

    for label_value, name in (
        (
            1,
            "positive_same_regime",
        ),
        (
            0,
            "negative_different_regime",
        ),
    ):
        mask = (
            pair_label
            == label_value
        )

        if not np.any(
            mask
        ):
            continue

        rows.append(
            {
                "pair_type": name,
                "n": int(
                    np.count_nonzero(
                        mask
                    )
                ),
                "mean_euclidean_distance": float(
                    np.mean(
                        euclidean[
                            mask
                        ]
                    )
                ),
                "std_euclidean_distance": float(
                    np.std(
                        euclidean[
                            mask
                        ]
                    )
                ),
                "mean_cosine_similarity": float(
                    np.mean(
                        cosine[
                            mask
                        ]
                    )
                ),
                "std_cosine_similarity": float(
                    np.std(
                        cosine[
                            mask
                        ]
                    )
                ),
                "cross_sequence_fraction": float(
                    np.mean(
                        ~same_sequence[
                            mask
                        ].astype(bool)
                    )
                ),
            }
        )

    positive_mask = (
        pair_label == 1
    )

    negative_mask = (
        pair_label == 0
    )

    positive_distance = (
        float(
            np.mean(
                euclidean[
                    positive_mask
                ]
            )
        )
        if np.any(
            positive_mask
        )
        else float("nan")
    )

    negative_distance = (
        float(
            np.mean(
                euclidean[
                    negative_mask
                ]
            )
        )
        if np.any(
            negative_mask
        )
        else float("nan")
    )

    positive_cosine = (
        float(
            np.mean(
                cosine[
                    positive_mask
                ]
            )
        )
        if np.any(
            positive_mask
        )
        else float("nan")
    )

    negative_cosine = (
        float(
            np.mean(
                cosine[
                    negative_mask
                ]
            )
        )
        if np.any(
            negative_mask
        )
        else float("nan")
    )

    summary = {
        "positive_mean_distance": (
            positive_distance
        ),
        "negative_mean_distance": (
            negative_distance
        ),
        "distance_margin": (
            negative_distance
            - positive_distance
        ),
        "positive_mean_cosine": (
            positive_cosine
        ),
        "negative_mean_cosine": (
            negative_cosine
        ),
        "cosine_margin": (
            positive_cosine
            - negative_cosine
        ),
    }

    return (
        rows,
        summary,
    )


def format_float(
    value: float,
    digits: int = 8,
) -> str:
    if not math.isfinite(
        value
    ):
        return "nan"

    return (
        f"{value:.{digits}f}"
    )


def build_summary(
    representations: np.ndarray,
    rotations: np.ndarray,
    regimes: np.ndarray,
    sequences: np.ndarray,
    sequence_stats: Sequence[
        Mapping[str, object]
    ],
    regime_stats: Sequence[
        Mapping[str, object]
    ],
    centroid_geometry: Mapping[
        str,
        float
    ],
    rotation_probe_rows: Sequence[
        Mapping[str, object]
    ],
    sequence_probe_result: Mapping[
        str,
        object
    ],
    pca_result: Mapping[
        str,
        np.ndarray
    ],
    pair_summary: Optional[
        Mapping[str, float]
    ],
) -> str:
    lines: List[str] = []

    lines.append(
        "=" * 96
    )

    lines.append(
        "Compact Rotation Bottleneck + Motion Alignment Analysis"
    )

    lines.append(
        "=" * 96
    )

    lines.append(
        f"Samples:                      "
        f"{representations.shape[0]}"
    )

    lines.append(
        f"Representation dimension:     "
        f"{representations.shape[1]}"
    )

    lines.append(
        f"Sequences:                    "
        f"{' '.join(sorted(set(sequences.tolist())))}"
    )

    lines.append(
        ""
    )

    global_stats = (
        representation_statistics(
            representations
        )
    )

    lines.append(
        "Global representation geometry"
    )

    lines.append(
        "-" * 96
    )

    lines.append(
        "Mean norm:                    "
        f"{format_float(float(global_stats['mean_norm']))}"
    )

    lines.append(
        "Centroid norm:                "
        f"{format_float(float(global_stats['centroid_norm']))}"
    )

    lines.append(
        "Within spread:                "
        f"{format_float(float(global_stats['within_spread']))}"
    )

    lines.append(
        "Total variance:               "
        f"{format_float(float(global_stats['total_variance']))}"
    )

    lines.append(
        "RMS scale:                    "
        f"{format_float(float(global_stats['rms_scale']))}"
    )

    lines.append(
        ""
    )

    lines.append(
        "Motion-regime geometry"
    )

    lines.append(
        "-" * 96
    )

    for row in regime_stats:
        lines.append(
            f"{str(row['regime_name']):<10s} "
            f"n={int(row['n']):6d} "
            f"centroid_norm="
            f"{format_float(float(row['centroid_norm']), 6)} "
            f"spread="
            f"{format_float(float(row['within_spread']), 6)} "
            f"var="
            f"{format_float(float(row['total_variance']), 6)}"
        )

    lines.append(
        ""
    )

    lines.append(
        "Cross-sequence centroid alignment"
    )

    lines.append(
        "-" * 96
    )

    same_distance = float(
        centroid_geometry[
            "same_regime_cross_sequence_distance"
        ]
    )

    different_distance = float(
        centroid_geometry[
            "different_regime_cross_sequence_distance"
        ]
    )

    lines.append(
        "Same-regime cross-seq distance: "
        f"{format_float(same_distance)}"
    )

    lines.append(
        "Diff-regime cross-seq distance: "
        f"{format_float(different_distance)}"
    )

    if (
        math.isfinite(
            same_distance
        )
        and math.isfinite(
            different_distance
        )
    ):
        lines.append(
            "Centroid distance margin:       "
            f"{format_float(different_distance - same_distance)}"
        )

    lines.append(
        ""
    )

    lines.append(
        "Rotation decodability from compact z_R"
    )

    lines.append(
        "-" * 96
    )

    for row in rotation_probe_rows:
        lines.append(
            f"{str(row['split']):<12s} "
            f"RMSE={format_float(float(row['vector_rmse']), 8)} "
            f"x_corr={format_float(float(row['x_corr']), 4)} "
            f"y_corr={format_float(float(row['y_corr']), 4)} "
            f"z_corr={format_float(float(row['z_corr']), 4)}"
        )

    lines.append(
        ""
    )

    lines.append(
        "Sequence-identity probe"
    )

    lines.append(
        "-" * 96
    )

    lines.append(
        "Linear training accuracy:       "
        f"{format_float(float(sequence_probe_result['training_accuracy']), 6)}"
    )

    lines.append(
        "Chance accuracy:                "
        f"{format_float(float(sequence_probe_result['chance_accuracy']), 6)}"
    )

    lines.append(
        "Accuracy above chance:          "
        f"{format_float(float(sequence_probe_result['accuracy_minus_chance']), 6)}"
    )

    lines.append(
        ""
    )

    lines.append(
        "PCA"
    )

    lines.append(
        "-" * 96
    )

    explained_ratio = (
        pca_result[
            "explained_variance_ratio"
        ]
    )

    cumulative = np.cumsum(
        explained_ratio
    )

    for index in range(
        min(
            8,
            explained_ratio.shape[0],
        )
    ):
        lines.append(
            f"PC{index + 1:<2d} "
            f"explained="
            f"{format_float(float(explained_ratio[index]), 6)} "
            f"cumulative="
            f"{format_float(float(cumulative[index]), 6)}"
        )

    if pair_summary is not None:
        lines.append(
            ""
        )

        lines.append(
            "Explicit alignment-pair geometry"
        )

        lines.append(
            "-" * 96
        )

        lines.append(
            "Positive mean distance:         "
            f"{format_float(float(pair_summary['positive_mean_distance']))}"
        )

        lines.append(
            "Negative mean distance:         "
            f"{format_float(float(pair_summary['negative_mean_distance']))}"
        )

        lines.append(
            "Distance margin:                "
            f"{format_float(float(pair_summary['distance_margin']))}"
        )

        lines.append(
            "Positive mean cosine:           "
            f"{format_float(float(pair_summary['positive_mean_cosine']))}"
        )

        lines.append(
            "Negative mean cosine:           "
            f"{format_float(float(pair_summary['negative_mean_cosine']))}"
        )

        lines.append(
            "Cosine margin:                  "
            f"{format_float(float(pair_summary['cosine_margin']))}"
        )

    lines.append(
        ""
    )

    lines.append(
        "Interpretation guide"
    )

    lines.append(
        "-" * 96
    )

    lines.append(
        "Desired evidence for successful motion-conditioned alignment:"
    )

    lines.append(
        "  1. compact z_R retains useful rotation decoding;"
    )

    lines.append(
        "  2. same-regime cross-sequence centroids are closer than "
        "different-regime centroids;"
    )

    lines.append(
        "  3. positive pair distances are lower than negative pair distances;"
    )

    lines.append(
        "  4. positive pair cosine similarity exceeds negative-pair cosine;"
    )

    lines.append(
        "  5. sequence identity is not trivially dominant in z_R;"
    )

    lines.append(
        "  6. held-out sequence 10 preserves rotation decodability without "
        "large latent displacement."
    )

    lines.append(
        "=" * 96
    )

    return "\n".join(
        lines
    )


def main() -> None:
    args = parse_args()
    validate_args(
        args
    )

    args.output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    blocks = load_all_blocks(
        paths=args.inputs,
        normalize=(
            args.normalize_representations
        ),
    )

    (
        representations,
        rotations,
        translations,
        regimes,
        sequences,
    ) = concatenate_blocks(
        blocks
    )

    sequence_stats = (
        compute_sequence_statistics(
            blocks
        )
    )

    regime_stats = (
        compute_regime_statistics(
            representations,
            regimes,
        )
    )

    (
        sequence_regime_rows,
        sequence_regime_centroids,
    ) = (
        compute_sequence_regime_centroids(
            blocks
        )
    )

    centroid_rows = (
        compute_centroid_distances(
            sequence_regime_centroids
        )
    )

    centroid_geometry = (
        summarize_centroid_geometry(
            centroid_rows
        )
    )

    rotation_probe_rows: List[
        Dict[str, object]
    ] = []

    if args.validation_sequences:
        rotation_probe_rows.append(
            evaluate_rotation_probe(
                representations=(
                    representations
                ),
                rotations=rotations,
                sequences=sequences,
                train_sequences=(
                    args.train_sequences
                ),
                evaluation_sequences=(
                    args.validation_sequences
                ),
                alpha=args.ridge_alpha,
                split_name="validation",
            )
        )

    if args.test_sequences:
        rotation_probe_rows.append(
            evaluate_rotation_probe(
                representations=(
                    representations
                ),
                rotations=rotations,
                sequences=sequences,
                train_sequences=(
                    args.train_sequences
                ),
                evaluation_sequences=(
                    args.test_sequences
                ),
                alpha=args.ridge_alpha,
                split_name="test",
            )
        )

    sequence_probe_result = (
        sequence_probe(
            representations=(
                representations
            ),
            sequences=sequences,
            alpha=(
                args.sequence_probe_alpha
            ),
        )
    )

    pca_result = compute_pca(
        representations=(
            representations
        ),
        requested_components=(
            args.pca_components
        ),
    )

    pair_rows = None
    pair_summary = None

    if args.pairs is not None:
        (
            pair_rows,
            pair_summary,
        ) = analyze_pair_archive(
            args.pairs
        )

    # ----------------------------------------------------------
    # Save tabular outputs.
    # ----------------------------------------------------------

    write_csv(
        args.output_dir
        / "sequence_statistics.csv",
        sequence_stats,
    )

    write_csv(
        args.output_dir
        / "regime_statistics.csv",
        regime_stats,
    )

    write_csv(
        args.output_dir
        / "sequence_regime_centroids.csv",
        sequence_regime_rows,
    )

    write_csv(
        args.output_dir
        / "centroid_distances.csv",
        centroid_rows,
    )

    write_csv(
        args.output_dir
        / "rotation_linear_probe.csv",
        rotation_probe_rows,
    )

    write_csv(
        args.output_dir
        / "sequence_probe.csv",
        [
            sequence_probe_result
        ],
    )

    if pair_rows is not None:
        write_csv(
            args.output_dir
            / "pair_geometry.csv",
            pair_rows,
        )

    global_stats = (
        representation_statistics(
            representations
        )
    )

    write_csv(
        args.output_dir
        / "representation_statistics.csv",
        [
            global_stats
        ],
    )

    np.savez_compressed(
        args.output_dir
        / "principal_components.npz",
        mean=(
            pca_result[
                "mean"
            ]
        ),
        components=(
            pca_result[
                "components"
            ]
        ),
        projected=(
            pca_result[
                "projected"
            ]
        ),
        explained_variance=(
            pca_result[
                "explained_variance"
            ]
        ),
        explained_variance_ratio=(
            pca_result[
                "explained_variance_ratio"
            ]
        ),
        sequence=sequences,
        motion_regime=regimes,
        rotation_gt=rotations,
        translation_gt=translations,
    )

    summary = build_summary(
        representations=(
            representations
        ),
        rotations=rotations,
        regimes=regimes,
        sequences=sequences,
        sequence_stats=(
            sequence_stats
        ),
        regime_stats=(
            regime_stats
        ),
        centroid_geometry=(
            centroid_geometry
        ),
        rotation_probe_rows=(
            rotation_probe_rows
        ),
        sequence_probe_result=(
            sequence_probe_result
        ),
        pca_result=pca_result,
        pair_summary=pair_summary,
    )

    summary_path = (
        args.output_dir
        / "analysis_summary.txt"
    )

    summary_path.write_text(
        summary + "\n",
        encoding="utf-8",
    )

    print()
    print(
        summary
    )

    print()

    print(
        "Saved analysis to: "
        f"{args.output_dir}"
    )


if __name__ == "__main__":
    main()